name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "APP_VERSION=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        id: buildx
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: traptitech
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/traptitech/traq-system-bot:latest
            ghcr.io/traptitech/traq-system-bot:${{ env.APP_VERSION }}
          cache-from: type=registry,ref=ghcr.io/traptitech/traq-system-bot:buildcache
          cache-to: type=registry,ref=ghcr.io/traptitech/traq-system-bot:buildcache,mode=max

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
